# bot settings
bot_token: 'YOUR_BOT_TOKEN' # support bot token
staffchat_id: 'SUPERGROUP_CHAT_ID' # eg. -123456789
owner_id: 'YOUR_TELEGRAM_ID'
spam_time: 5 * 60 * 1000 # time (in MS) in which user may send 5 messages
spam_cant_msg: 5

parse_mode: 'MarkdownV2' # DO NOT CHANGE!

allow_private: false # Allow / disallow option for staff to chat privately
direct_reply: false # Set this to true to just forward staff users to a user chat when allow_private
auto_close_tickets: true # Close tickets after answering
anonymous_tickets: true # Include userid in tickets or not
show_auto_replied: false # Send auto replied msgs to staff chat
show_user_ticket: false # Show ticket id to user

signal_enabled: false # Enable/disable signal
signal_number: '+12345689' # Your signal number / account

web_server: false # Enable/disable web server
web_server_port: 8080 # Port for web server

dev_mode: true # Enable/disable dev mode

# customize your language
language:
  startCommandText: 'Welcome in our support chat! Ask your question here.'
  faqCommandText: 'Get this bot at: [github.com](https://github.com/bostrot/telegram-support-bot)'
  helpCommandText: "*Available commands:*\n/help\n/faq\n/id"
  helpCommandStaffText: "*Available commands:*\n
    /start - Get a little introduction\n
    /faq - Show frequently asked questions\n
    /open - *Staff* Shows a list of open tickets\n
    /reopen - *Staff* Reopen a closed ticket\n
    /close - *Staff* Reply to a ticket with this to close and unban\n
    /clear - *Staff* Closes all tickets\n
    /ban - *Staff* Ban a user from the chat\n
    /unban - *Staff* Unban a user"
  contactMessage: "Thank you for contacting us. We will answer as soon as possible.\n"
  blockedSpam: 'You sent quite a number of questions in the last while. Please calm down and wait until staff reviews them.'
  ticket: 'Ticket'
  closed: 'closed'
  acceptedBy: 'was accepted by'
  dear: 'Hi'
  regards: 'Regards,'
  from: 'from'
  language: 'Language'
  msg_sent: 'Message sent to user'
  file_sent: 'File sent to user'
  usr_with_ticket: 'User with ticket'
  banned: 'banned'
  replyPrivate: 'Reply in private'
  services: 'Select a service from the list below'
  customer: 'customer'
  msgForwarding: 'You messages will now be forwarded to vendors of the group: '
  back: 'Go back'
  whatSubCategory: 'Which subcategory describes your needs the best? '
  prvChatEnded: 'Private chat ended.'
  prvChatOpened: 'Private Chat opened with customer.'
  prvChatEnd: 'End Private chat'
  prvChatOpenedCustomer: 'Opened private chat'
  instructionsSent: 'Instructions were sent to you in private chat.'
  openTickets: 'Open Tickets'
  support: 'Support'
  prvChatOnly: 'This command can be used in private chat only.'
  ticketClosed: 'Your ticket was closed by our staff. You can open a new ticket at any time.'
  links: 'Direct support links'
  textFirst: 'Please send us a message before sending an image so that we can help you better.'
  ticketClosedError: 'You cannot reply to a closed ticket.'
  automatedReply: 'This is an automated reply.'
  automatedReplyAuthor: 'BottyBot.'
  doesntHelp: 'This does not help.'
  automatedReplySent: 'Automated reply was send to the user.'
  ticketReopened: 'Ticket reopened.'

autoreply:
  - question: 'install'
    answer: "If you want to install the bot, you can use the following link:\n\
      [Getting Started](https://github.com/bostrot/telegram-support-bot/wiki/Getting-started)\n\n\
      Alternatively you can also use our one-click setup & hosting service:\n\
      [Botspace](https://botspace.bostrot.com/)"
  - question: 'are you sure?'
    answer: 'Yes.'
# categories:
#  - name: "Category1"
#    subgroups:
#    - name: "Sub1"
#      group_id: "-12345678910"
#    - name: "Sub2"
#      group_id: "-12345678910"
#    - name: "Sub3"
#      group_id: "-12345678910"
#  - name: "Category2"
#    subgroups:
#    - name: "Sub4"
#      group_id: "-12345678910"
#    - name: "Sub5"
#      group_id: "-12345678910"
#    - name: "Sub6"
#      group_id: "-12345678910"
#  - name: "Category with no subcategories"
#    group_id: "-12345678910"
#  - name: "Admin Chat"
#    group_id: "-12345678910"
#  - name: "Contact"
#    msg: "Check out our Website"

